{% set name = "napari-vedo-bridge" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b3227812bd681cfaba881367c470d4b4a8dd4468009b663e1546178f655bafe1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - numpy
    - python >=3.8
    - qtpy
    - vedo >=2023.4.6
    - vtk

test:
  imports:
    - napari_vedo_bridge
    - napari_vedo_bridge._cutter_widget
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/jo-mueller/napari-vedo-bridge
  summary: Transfer mesh data between napari and vedo for interactive processing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jo-mueller
